### ISSUE TITLE
Timeout on subscription ?

### ISSUE THREAD

**Issue by jmaupoux** [sorare/actioncable#1]
Hi,

I noticed my subscription does not receive data anymore after 2 hours.
No callback executed (no disconnect or reject), it seems connected but nothing comes.

The duration is always  "2 hours".

Any idea ?

Thanks,

**Comment by redox** [comment]
Indeed, we have an expiration set to 7200 seconds (2 hours) on our anycable backend. That being said, if you implement the `ping/pong` the right way, you should detect no `pong` is coming back and therefore reconnect.

**Comment by jmaupoux** [comment]
Actually it seems the Typescript module doesn't offer much possibilities.

Everything being private, I can only subscribe and listen on callbacks.

Do you suggest the right way would be to fork it to "open" the client ?

**Comment by redox** [comment]
> Do you suggest the right way would be to fork it to "open" the client ?

hmmm, not sure; but if think about a way to patch this library to let you do what you need, I would love to merge a PR!

**Comment by jmaupoux** [comment]
I would say "reproductibility" is a challenge on this issue. Waiting for 2 hours is painful.

I notice however than calling `.terminate()` instead of `.close()` in heartbeat triggers the `disconnected` callback - but not always. First step.

I ll keep trying few things this way and keep you posted if I get a satisfying result.
